name: Coderco Custom Action CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v2


        - name: hello word custom action
          uses: OsmanA12/custom-actions@main
          with:
            who-to-greet: 'Team' 